MarketPlace.Host/Areas/Admin/Controllers/ProductController.cs
using Infa.Application.Interfaces;
using Infa.Domain.ViewModels.Common;
using Infa.Domain.ViewModels.Products;
using MarketPlace.Web.Areas.Admin.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Host.Areas.Admin.Controllers
{
    public partial class ProductController : AdminBaseController
    {
        private readonly IProductServices _productServices;

        public ProductController(IProductServices productServices)
        {
            _productServices = productServices;
        }
    }
    public partial class ProductController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("FilterProducts")]
        public async Task<IActionResult> FilterProducts(FilterProductsVM filterProductsVM)
        {
            return View(await _productServices.FilterProducts(filterProductsVM));
        }

        [HttpGet]
        public async Task<IActionResult> AcceptProduct(string Id)
        {
            await _productServices.AcceptProduct(Id);
            return RedirectToAction("FilterProducts");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RejectProduct(string Id, RejectItemVM rejectItemVM)
        {
            if (ModelState.IsValid)
            {
                await _productServices.RejectProduct(Id, rejectItemVM);
                return RedirectToAction("FilterProducts");
            }
            return View();
        }
    }
}

MarketPlace.Host/Areas/Seller/Controllers/ProductController.cs
using Infa.Application.Extentions;
using Infa.Application.Interfaces;
using Infa.Application.Utils;
using Infa.Domain.ViewModels.Products;
using MarketPlace.Application.Extensions;
using MarketPlace.Application.Utils;
using MarketPlace.Host.Areas.User.Controllers;
using MarketPlace.Web.Http;
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Host.Areas.Seller.Controllers
{
    public partial class ProductController : SellerBaseController
    {
        private readonly ISellerServices _sellerServices;
        private readonly IProductServices _productServices;
        public ProductController(ISellerServices sellerServices, IProductServices productServices)
        {
            _sellerServices = sellerServices;
            _productServices = productServices;
        }
    }
    public partial class ProductController : SellerBaseController
    {
        [HttpGet("ProductsList")]
        public async Task<IActionResult> Index(FilterProductsVM productsVM)
        {
            productsVM.SellerId = await _sellerServices.GetLastActiveSellerId(User.GetUserId());
            productsVM.FilterProductState = FilterProductState.All;
            productsVM = await _productServices.FilterProducts(productsVM);
            return View(productsVM);
        }

        [HttpGet("CreateProduct")]
        public async Task<IActionResult> CreateProduct()
        {
            ViewBag.Categories = await _productServices.GetAllCategoriesByParentId(null);
            return View();
        }

        [HttpPost("CreateProduct")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProduct(CreateProductVM productVM, IFormFile postedFile)
        {
            if (ModelState.IsValid)
            {
                var seller = await _sellerServices.GetLastActiveSellerId(User.GetUserId());
                var result = await _productServices.CreateProduct(productVM, postedFile,seller);
                switch (result)
                {
                    case CreateProductResult.Success:
                        TempData[SuccessMessage] = $"محصول مورد نظر با عنوان {productVM.Title} با موفقیت ثبت شد";
                        return RedirectToAction("Index");

                    case CreateProductResult.HasNoImage:
                        TempData[WarningMessage] = "لطفا تصویر محصول را وارد نمایید";
                        break;

                    case CreateProductResult.Fail:
                        TempData[ErrorMessage] = "عملیات ثبت محصول با خطا مواجه شد";
                        break;
                    default:
                        break;
                }
            }
            ViewBag.Categories = await _productServices.GetAllCategoriesByParentId(null);
            return View();
        }


        [HttpGet("product-categories/{parentId}")]
        public async Task<IActionResult> GetProductCategoriesByParent(string parentId)
        {
            var categories = await _productServices.GetAllCategoriesByParentId(parentId);

            return JsonResponseStatus.SendStatus(JsonResponseStatusType.Success, "اطلاعات دسته بندی ها", categories);
        }


        [HttpGet("edit-product/{productId}")]
        public async Task<IActionResult> EditProduct(string productId)
        {
            var product = await _productServices.GetProductForEdit(productId);
            if (product == null) return NotFound();
            ViewBag.Categories = await _productServices.GetAllCategories();
            return View(product);
        }
    }
}

MarketPlace.Host/Areas/Seller/ViewComponents/SellerSideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MarketPlace.Host.Areas.Seller.ViewComponents
{
    public class SellerSideBarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("SellerSideBar");
        }
    }
}

MarketPlace.Host/Areas/Seller/Views/Product/CreateProduct.cshtml
@using Infa.Domain.Models.SellersProduct
@model Infa.Domain.ViewModels.Products.CreateProductVM
@{
    ViewData["Title"] = "ثبت محصول";
    var categories = ViewBag.Categories as List<Category>;
}




<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form asp-area="Seller" asp-controller="Product" asp-action="CreateProduct" enctype="multipart/form-data" id="create_product_form">
                                            <label>نام محصول</label>
                                            <input asp-for="Title">
                                            <span class="text-danger" asp-validation-for="Title"></span>
                                            <br />
                                            <label>قیمت محصول</label>
                                            <input asp-for="Price">
                                            <span class="text-danger" asp-validation-for="Price"></span>
                                            <br />
                                            <label>توضیحات کوتاه محصول</label>
                                            <br />
                                            <textarea asp-for="ShortDescription" style="width: 100%" rows="3"></textarea>
                                            <span class="text-danger" asp-validation-for="ShortDescription"></span>
                                            <br />
                                            <label>توضیحات محصول</label>
                                            <textarea asp-for="Description" style="width: 100%" rows=10></textarea>
                                            <span class="text-danger" asp-validation-for="Description"></span>
                                            <br />
                                            <label>
                                                <input type="checkbox" name="@nameof(Model.IsActive)" value="true" /> فعال / غیر فعال
                                            </label>
                                            <br />
                                            <div class="col-md-9">
                                                <img style="border-radius:50%; width:150px"
                                                     id="imgPreview" />
                                                <input accept="image/*" id="photo" type="file" name="postedFile" />
                                            </div>
                                            <hr />
                                            @if (categories != null && categories.Any())
                                            {
                                                @foreach (var category in categories.Where(s => s.ParentId == null))
                                                {
                                                    <ul>
                                                        <li>
                                                            <label>
                                                                <input type="checkbox" name="@nameof(Model.SelectedCategories)" value="@category.Id" main_category_checkbox="@category.Id" /> @category.Title
                                                            </label>

                                                            <div id="sub_categories_@category.Id" style="display: none">

                                                                @foreach (var subCategory in categories.Where(s => s.ParentId == category.Id))
                                                                {
                                                                    <label>
                                                                        <input type="checkbox" name="@nameof(Model.SelectedCategories)" value="@subCategory.Id" main_category_checkbox="@subCategory.Id" parent-category-id="@category.Id" /> @subCategory.Title
                                                                    </label>
                                                                    <div id="sub_categories_@subCategory.Id" style="display: none">

                                                                        @foreach (var secondSubCategory in categories.Where(s => s.ParentId == subCategory.Id))
                                                                        {
                                                                            <label>
                                                                                <input type="checkbox" name="@nameof(Model.SelectedCategories)" value="@secondSubCategory.Id" parent-category-id="@subCategory.Id" /> @secondSubCategory.Title
                                                                            </label>
                                                                        }
                                                                    </div>
                                                                }
                                                            </div>
                                                        </li>

                                                    </ul>
                                                    <hr />
                                                }
                                            }

                                            <label>رنگ محصول</label>
                                            <input type="text" placeholder="رنگ محصول" id="product_color_name_input">

                                            <label>قیمت مضاف رنگ محصول</label>
                                            <input type="number" placeholder="قیمت مضاف رنگ محصول" id="product_color_price_input">

                                            <button class="btn btn-success" id="add_color_button">افزودن رنگ</button>
                                            <br />
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th>نام رنگ</th>
                                                            <th>قیمت</th>
                                                            <th>دستورات</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody id="list_of_product_colors">
                                                    </tbody>
                                                </table>
                                            </div>
                                            <div class="save_button primary_btn default_button">
                                                <button type="submit">افزودن</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.Host/Areas/Seller/Views/Product/EditProduct.cshtml
@using Infa.Domain.Models.SellersProduct
@using Infa.Application.Utils
@model Infa.Domain.ViewModels.Products.EditProductVM
@{
    ViewData["Title"] = "ویرایش " + Model.Title;
    var categories = ViewBag.Categories as List<Category>;
}





<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form asp-area="Seller" asp-controller="Product" asp-action="CreateProduct" enctype="multipart/form-data" id="create_product_form">
                                            <input type="hidden" asp-for="Id" />
                                            <label>نام محصول</label>
                                            <input asp-for="Title">
                                            <span class="text-danger" asp-validation-for="Title"></span>
                                            <br />
                                            <label>قیمت محصول</label>
                                            <input asp-for="Price">
                                            <span class="text-danger" asp-validation-for="Price"></span>
                                            <br />
                                            <label>توضیحات کوتاه محصول</label>
                                            <br />
                                            <textarea asp-for="ShortDescription" style="width: 100%" rows="10"></textarea>
                                            <span class="text-danger" asp-validation-for="ShortDescription"></span>
                                            <br />
                                            <label>توضیحات محصول</label>
                                            <textarea asp-for="Description" ckeditor="1"></textarea>
                                            <span class="text-danger" asp-validation-for="Description"></span>
                                            <br />
                                            <label>
                                                <input type="checkbox" name="@nameof(Model.IsActive)" value="true" @(Model.IsActive ? "checked" : "") /> فعال / غیر فعال
                                            </label>
                                            <br />
                                            <input type="file" name="productImage" accept=".png,.jpeg" />
                                            <div class="col-md-9">

                                                <img src="@(FilePath.ProductThumbnailImage + Model.Image)" />
                                            </div>
                                            <hr />
                                            @if (categories != null && categories.Any())
                                            {
                                                @foreach (var category in categories.Where(s => s.ParentId == null))
                                                {
                                                    var isParentCategorySelected = Model.Categories.Select(x=>x.Id).Any(s => s == category.Id);
                                                    <ul>
                                                        <li>
                                                            <label>
                                                                <input type="checkbox" name="@nameof(Model.Categories)" value="@category.Id" main_category_checkbox="@category.Id" @(isParentCategorySelected ? "checked" : "") /> @category.Title
                                                            </label>

                                                            <div id="sub_categories_@category.Id" style="display: @(isParentCategorySelected ?"block":"none")">

                                                                @foreach (var subCategory in categories.Where(s => s.ParentId == category.Id))
                                                                {
                                                                    var isSubCategorySelected = Model.Categories.Select(x=>x.Id).Any(s => s == category.Id);
                                                                    <label>
                                                                        <input type="checkbox" name="@nameof(Model.Categories)" value="@subCategory.Id" main_category_checkbox="@subCategory.Id" parent-category-id="@category.Id" @(isSubCategorySelected ? "checked" : "") /> @subCategory.Title
                                                                    </label>
                                                                    <div id="sub_categories_@subCategory.Id" style="display: @(isSubCategorySelected ?"block":"none")">

                                                                        @foreach (var secondSubCategory in categories.Where(s => s.ParentId == subCategory.Id))
                                                                        {
                                                                            var isSecondSubCategorySelected = Model.Categories.Select(x=>x.Id).Any(s => s == secondSubCategory.Id);
                                                                            <label>
                                                                                <input type="checkbox" name="@nameof(Model.Categories)" value="@secondSubCategory.Id" parent-category-id="@subCategory.Id" @(isSecondSubCategorySelected ? "checked" : "") /> @secondSubCategory.Title
                                                                            </label>
                                                                        }
                                                                    </div>
                                                                }
                                                            </div>
                                                        </li>

                                                    </ul>
                                                    <hr />
                                                }
                                            }

                                            <label>رنگ محصول</label>
                                            <input type="text" placeholder="رنگ محصول" id="product_color_name_input">

                                            <label>قیمت مضاف رنگ محصول</label>
                                            <input type="number" placeholder="قیمت مضاف رنگ محصول" id="product_color_price_input">

                                            <button class="btn btn-success" id="add_color_button">افزودن رنگ</button>
                                            <br />
                                            <br />
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th>نام رنگ</th>
                                                            <th>قیمت</th>
                                                            <th>دستورات</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody id="list_of_product_colors">
                                                        @if (Model.ProductColors != null && Model.ProductColors.Any())
                                                        {
                                                            foreach (var color in Model.ProductColors)
                                                            {
                                                                <tr color-table-item="@color.ColorName-@color.Price">
                                                                    <td> @color.ColorName </td>
                                                                    <td> @color.Price </td>
                                                                    <td> <a class="btn btn-danger text-white" onclick="removeProductColor('@color.ColorName-@color.Price')">حذف</a> </td>
                                                                </tr>
                                                            }
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>

                                            <div class="save_button primary_btn default_button">
                                                <button type="submit">افزودن</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.Host/Areas/Seller/Views/Product/Index.cshtml
@using Infa.Application.Utils
@using MarketPlace.Application.Extensions
@using MarketPlace.Application.Utils
@model Infa.Domain.ViewModels.Products.FilterProductsVM
@{
    ViewData["Title"] = "لیست محصولات";
}


<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SellerSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <div class="table-responsive">
                                @if (Model.Products != null && Model.Products.Any())
                                {
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>تصویر</th>
                                                <th>عنوان محصول</th>
                                                <th>وضعیت</th>
                                                <th>دستورات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var product in Model.Products)
                                            {
                                                <tr>
                                                    <td>
                                                        <img src="@(FilePath.ProductThumbnailImage + product.ImageName)" width="75" />
                                                    </td>
                                                    <td>@product.Title</td>
                                                    <td>
                                                        <span class="danger">
                                                            @Html.DisplayFor(Model=>product.ProductAcceptanceState)
                                                        </span>
                                                        @if (product.ProductAcceptanceState == Infa.Domain.Models.SellersProduct.ProductAcceptanceState.Rejected)
                                                        {
                                                            <hr />
                                                            <div class="text-danger">
                                                                <p> @product.ProductAcceptOrRejectDescription</p>
                                                            </div>
                                                        }
                                                    </td>
                                                    <td><a asp-area="Seller" asp-controller="Product" asp-action="EditProduct" asp-route-productId="@product.Id" class="view">ویرایش</a></td>



                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                                else
                                {
                                    <partial name="_NoItemFound" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>