MarketPlace.Host/Areas/User/Controllers/TicketController.cs
using GoogleReCaptcha.V3.Interface;
using Infa.Application.Extentions;
using Infa.Application.Interfaces;
using Infa.Domain.ViewModels.Contact;
using Microsoft.AspNetCore.Mvc;
using static Infa.Domain.ViewModels.Contact.FilterTicketVM;

namespace MarketPlace.Host.Areas.User.Controllers
{
    public partial class TicketController : BaseController
    {
        private readonly IUserServices _userServices;
        private readonly ICaptchaValidator _captchaValidator;
        private readonly IContactServices _contactServices;

        public TicketController
            (
            IUserServices userServices,
            ICaptchaValidator captchaValidator,
            IContactServices contactServices
            )
        {
            _userServices = userServices;
            _captchaValidator = captchaValidator;
            _contactServices = contactServices;
        }
    }
    public partial class TicketController : BaseController
    {
        [Route("tickets")]
        public async Task<IActionResult> Index(FilterTicketVM ticketVM )
        {

            ticketVM.FilterTicketStates = FilterTicketState.NotDeleted;
            ticketVM.OrderBy = FilterTicketOrder.CreateDate_DES;
            ticketVM.Tickets = await _contactServices.FilterTickets(ticketVM, User.GetUserId());
            return View(ticketVM);
        }

        #region SubmitTicket

        [Route("SubmitTicket")]
        public IActionResult SubmitTicket()
        {
            return View();
        }

        [Route("SubmitTicket")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitTicket(AddUserTicketVM ticketVM)
        {
            if (await _captchaValidator.IsCaptchaPassedAsync(ticketVM.Token))
            {
                if (ModelState.IsValid)
                {
                    var result = await _contactServices.AddTicket(ticketVM, User.GetUserId());

                    switch (result)
                    {
                        case AddTicketResult.Success:
                            TempData[SuccessMessage] = "تیکت شما با موفقیت ثبت شد";
                            TempData[InfoMessage] = "پاسخ شما به زودی ارسال خواهد شد";
                            return Redirect("user");

                        case AddTicketResult.Failure:
                            TempData[ErrorMessage] = "مشکلی پیش امد لطفا دوباره تلاش کنید";
                            return View(ticketVM);

                        default:
                            break;
                    }
                }
                TempData[ErrorMessage] = "اعتبار سنجی انجام نشد";
            }
            return View(ticketVM);
        }

        #endregion


        #region TicketDetail


        [Route("tickets/{ticketId}")]
        [HttpGet]
        public async Task<IActionResult> TicketDetail(string ticketId)
        {
            var ticket = await _contactServices.GetTicketDetail(ticketId, User.GetUserId());
            if (ticket == null) return NotFound();

            return View(ticket);
        }
        
        
        
        #endregion

    }
}

MarketPlace.Host/Areas/User/Views/Ticket/Index.cshtml
@model Infa.Domain.ViewModels.Contact.FilterTicketVM
@{
    ViewData["title"] = "تیکت ها";
}

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-1 col-md-1 col-lg-1">
                    <!-- Nav tabs -->
                    <div class="dashboard_tab_button">
                        @await Component.InvokeAsync("SideBar")
                    </div>
                </div>
                <div class="col-sm-9 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade" id="dashboard">
                            <h3>داشبورد </h3>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با <a href="#">سفارشات اخیر</a>لورم ایپسوم متن <a href="#">لورم ایپسوم متن ساختگی با تولید</a> لورم <a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</a></p>
                        </div>
                        <div class="tab-pane fade active show" id="downloads">
                            <div class="table-responsive">
                                @if (Model.Tickets != null && Model.Tickets.Any())
                                {
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>موضوع</th>
                                                <th>تاریخ</th>
                                                <th>اولویت</th>
                                                <th>بخش مورد نظر</th>
                                                <th>وضعیت</th>
                                                <th>جزییات</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model.Tickets)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(Model=>item.Title)</td>
                                                    <td>@item.CreateAt</td>
                                                    <td>@Html.DisplayFor(Model=>item.TicketPriority)</td>
                                                    <td>@Html.DisplayFor(Model=>item.TicketSection)</td>
                                                    <td>@Html.DisplayFor(Model=>item.TicketState)</td>
                                                    <td><a href="http://localhost:5076/tickets/@item.Id" class="view">نمایش جزییات</a></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }

                                else
                                {
                                    <partial name="_NoItemFound" />
                                }
                            </div>
                        </div>
                        <div class="dashboard_tab_button row">
                            <ul role="button" class="nav flex-column dashboard-list row col-md-12">
                                <li class="col-md-3"><a asp-area="User" asp-controller="Ticket" asp-action="SubmitTicket" class="nav-link">ثبت تیکت جدید</a></li>

                            </ul>
                            <ul role="button" class="nav flex-column dashboard-list row col-md-12">
                                <li class="col-md-3"><a asp-area="User" asp-controller="home" asp-action="index" class="nav-link">بازگشت</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2 ">
                    <!-- Nav tabs -->
                    <div class="dashboard_tab_button">
                        @await Component.InvokeAsync("LeftSideBar")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.Host/Areas/User/Views/Ticket/SubmitTicket.cshtml
@model Infa.Domain.ViewModels.Contact.AddUserTicketVM
@using Infa.Domain.Models.Contacts
@{
    ViewData["Title"] = "پشتیبانی";
}





<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form asp-area="User" asp-controller="Ticket" asp-action="SubmitTicket">
                                            <partial name="_CaptchaInput" />
                                            <label>موضوع</label>
                                            <input asp-for="Title" type="text">
                                            <span asp-validation-for="Title" class="text-danger"></span>

                                            <div class="form-group row col-md-12 ">
                                                <div class="form-group col-md-6">
                                                    <label>بخش مورد نظر</label>
                                                    <select asp-for="TicketSection" asp-items="@Html.GetEnumSelectList<TicketSection>()" class="form-control"></select>
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label>اولویت </label>
                                                    <select asp-for=TicketPriority asp-items="@Html.GetEnumSelectList<TicketPriority>()" class="form-control"></select>
                                                </div>
                                            </div>
                                            <label>متن</label>
                                            <textarea class="form-control" asp-for="Text" rows="10"></textarea>
                                            <span asp-validation-for="Text" class="text-danger"></span>
                                            <br>

                                            <div class="save_button primary_btn default_button">
                                                <button type="submit">ذخیره</button>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.Host/Areas/User/Views/Ticket/TicketDetail.cshtml
@using Infa.Application.Utils
@using Infa.Domain.ViewModels.Contact
@model Infa.Domain.ViewModels.Contact.TicketDetailsVM
@{
    ViewData["Title"] = Model.Ticket.Title;
}



<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("SideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>


                            <hr />
                            <ul class="messages" id="messages">
                                @if (Model.TicketMessage != null && Model.TicketMessage.Any())
                                {
                                    foreach (var message in Model.TicketMessage)
                                    {
                                        <li class="message @(message.SenderId == Model.Ticket.OwnerId ? "right" : "left") appeared">
                                            <div class="avatar">
                                                <img  src="@(!string.IsNullOrEmpty(Model.User.Avatar) ? FilePath.UserAvatarOrigin + Model.User.Avatar : FilePath.DefaultAvatar)" />
                                            </div>
                                            <div class="text_wrapper">
                                                <div class="time">
                                                    @message.CreateAt ساعت 
                                                </div>
                                                <div class="text" style="font-size: 16px">
                                                    @Html.Raw(message.Text)
                                                </div>
                                            </div>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>